<?php

namespace GlimeshClient\Traits;

/**
 * Autogenerated Trait, maps field keys to objects
 *
 * @author Adam Hebden <adam@adamhebden.com>
 * @copyright 2022 Adam Hebden
 * @license GPL-3.0-or-later
 * @package GlimeshClient
 * @generated 2022-06-23
 */
trait FieldMappingTrait
{
    public static array $mappingMultiple = [
        'bans'                  => \GlimeshClient\Objects\ChannelBan::class,
        'categories'            => \GlimeshClient\Objects\Category::class,
        'channels'              => \GlimeshClient\Objects\Channel::class,
        'chatMessages'          => \GlimeshClient\Objects\ChatMessage::class,
        'followers'             => \GlimeshClient\Objects\Follower::class,
        'following'             => \GlimeshClient\Objects\Follower::class,
        'followingLiveChannels' => \GlimeshClient\Objects\Channel::class,
        'homepageChannels'      => \GlimeshClient\Objects\Channel::class,
        'metadata'              => \GlimeshClient\Objects\StreamMetadata::class,
        'moderationLogs'        => \GlimeshClient\Objects\ChannelModerationLog::class,
        'moderators'            => \GlimeshClient\Objects\ChannelModerator::class,
        'socials'               => \GlimeshClient\Objects\UserSocial::class,
        'streams'               => \GlimeshClient\Objects\Stream::class,
        'subcategories'         => \GlimeshClient\Objects\Subcategory::class,
        'tags'                  => \GlimeshClient\Objects\Tag::class,
        'tokens'                => \GlimeshClient\Interfaces\ChatMessageToken::class,
        'users'                 => \GlimeshClient\Objects\User::class,
    ];

    public static array $mappingSingle = [
        'category'    => \GlimeshClient\Objects\Category::class,
        'channel'     => \GlimeshClient\Objects\Channel::class,
        'chatMessage' => \GlimeshClient\Objects\ChatMessage::class,
        'followers'   => \GlimeshClient\Objects\Follower::class,
        'metadata'    => \GlimeshClient\Objects\ChatMessageMetadata::class,
        'moderator'   => \GlimeshClient\Objects\User::class,
        'myself'      => \GlimeshClient\Objects\User::class,
        'status'      => \GlimeshClient\Objects\Enums\ChannelStatus::class,
        'stream'      => \GlimeshClient\Objects\Stream::class,
        'streamer'    => \GlimeshClient\Objects\User::class,
        'subcategory' => \GlimeshClient\Objects\Subcategory::class,
        'user'        => \GlimeshClient\Objects\User::class,
    ];
}
