<?php

namespace GlimeshClient\Objects;

/**
 * A chat message sent to a channel by a user.
 */
class ChatMessage extends AbstractObjectModel
{
    /**
     * Description not provided
     *
     * @var Channel
     */
    protected $channel;

    /**
     * Description not provided
     *
     * @var string
     */
    protected $id;

    /**
     * Description not provided
     *
     * @var DateTime
     */
    protected $insertedAt;

    /**
     * Was this message generated by our system for a follow
     *
     * @var Boolean
     */
    protected $isFollowedMessage;

    /**
     * Was this message generated by our system for a subscription
     *
     * @var Boolean
     */
    protected $isSubscriptionMessage;

    /**
     * The chat message.
     *
     * @var String
     */
    protected $message;

    /**
     * Description not provided
     *
     * @var ArrayObject<ChatMessageToken>
     */
    protected $tokens;

    /**
     * Description not provided
     *
     * @var DateTime
     */
    protected $updatedAt;

    /**
     * Description not provided
     *
     * @var User
     */
    protected $user;
}
